### PR TITLE
Workaround for unreliable world load / unload events, possibly fixes #4

### LINKED ISSUE #4: [Patch Request] IC2 Cable bug
**Link to the bug IC2's issue tracker**
https://bt.industrial-craft.net/view.php?id=1959
https://forum.industrial-craft.net/thread/16379-ic2-enet-bug-1-12/

**Describe the bug**
Sometime when switching Dimensions and then going back to the Dimension where the cables are, all Cables in the Dimensions will be instantly disconnected.

**To Reproduce**
1. Place IC2 cables with Machines
2. Go to the nether
3. Go back
4. see issue.

**Expected behavior**
That they not Disconnect.

### PR DESCRIPTION
**Pull request by ThePixelbrain**
As has been previously mentioned by Player on the [IC2 Forums](https://forum.industrial-craft.net/thread/16379-ic2-enet-bug-1-12/?postID=219464#post219464), the IC2 Energy Net breaks because of unreliable world load / unload events. If the events are wrongly ordered or missing, the IC2 Energy Net can break.

`WorldData` saves a static `ConcurrentMap<Integer, WorldData>`. Every time something world related is needed (Energy Net, Trading Market, WindSim) it is retrieved by the dimension ID. Entries on the map are removed through world unload events. If a world unload event goes missing or a world load event is executed afterwards, the old, unloaded world will still be referenced. This becomes an issue in the following scenario:
1. World is being unloaded
2. World Unload event fires
3. World Load event fires, but the world is actually unloaded
4. World is being loaded again, new World object gets created
5. `WorldData.get()` is called and returns the old, dead world object. 
6. All Energy Net tiles fail to register to the Energy Net.

I added a workaround to prevent this from happening. I check if the world objects are still identical on world load. If they are not, I instantiate a new `WorldData` object. I also clear the map completely after a `FMLServerStoppedEvent`, since no worlds should exist anymore at that time.

### CODE REVIEW

File: projects/IC2-Patched/patches/minecraft/ic2/core/IC2.java.patch [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+@@ -409,6 +410,11 @@
+    @EventHandler
+    public void serverStart(FMLServerStartingEvent event) {
+       event.registerServerCommand(new CommandIc2());
++   }
++
++   @EventHandler
++   public void onServerStopped(FMLServerStoppedEvent event) {
++      WorldData.resetMaps();
+    }
```
Comment (Su5eD) [inline projects/IC2-Patched/patches/minecraft/ic2/core/IC2.java.patch:20]: We should move this event listener to the `mods.su5ed.ic2patcher.Patcher` to keep ASM patches at minimum. Also in order to access the injected resetMaps method, you'll likely need to replace the ic2 dependency in gradle with a project dep on `IC2-Patched`.

**Review by Su5eD — CHANGES_REQUESTED** [review]

**Review by Su5eD — APPROVED** [review]
